[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "DsPBXEEbHUt3Vdyx2qdesFLmDRTRndwA2v6qfdjAxL1T"
solana_program_practice = "9u81MKiqMR7oRyM5M9v666eKoWqEMRiR9bF5amjmyEug"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
