name: Anchor

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOLANA_VERSION: v1.18.8
  ANCHOR_VERSION: v0.30.0

jobs:

  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        
    - name: Install Solana
      run: sh -c "$(curl -sSfL https://release.solana.com/${{ env.SOLANA_VERSION }}/install)"
      
    - name: Install Yarn
      run: npm install -g yarn
      
    - name: Install Anchor
      run: cargo install --git https://github.com/coral-xyz/anchor --tag ${{ env.ANCHOR_VERSION }} anchor-cli --locked
      
  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: $HOME/.cargo/bin/anchor build

  test:
    needs: setup  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Test
      run: $HOME/.cargo/bin/anchor test