name: Anchor

on:
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '18.20.2'
  SOLANA_VERSION: '1.18.8'
  ANCHOR_VERSION: '0.30.0'

jobs:

  setup:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: metadaoproject/setup-anchor@v2
      with:
        anchor-version: ${{ env.ANCHOR_VERSION }}
        solana-cli-version: ${{ env.SOLANA_VERSION }}
        node-version: ${{ env.NODE_VERSION }}

    - name: Anchor Build
      run: anchor build