name: Anchor

on:
  pull_request:
    branches: [main]

env:
  SOLANA_VERSION: v1.18.8
  ANCHOR_VERSION: v0.30.0

jobs:

  setup:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: metadaoproject/setup-anchor@v2.1
      with:
        anchor-version: ${{ env.ANCHOR_VERSION }}
        solana-cli-version: ${{ env.SOLANA_VERSION }}

    - name: Anchor Build
      run: anchor build