name: Cargo

on:
  pull_request:
    branches: [main]

jobs:

  setup:
    name: Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: fmt
      run: cargo fmt --all -- --check

    - name: clippy
      run: cargo clippy -- -D warnings
